# ROAD dataset CAN ID to image

In [1]:
import numpy as np
import os
import pandas as pd
from PIL import Image

In [2]:
data_root = 'D:/dataset/road-dataset-master/road/signal_extractions'

In [3]:
save_path = os.path.join(data_root, 'image_64')

if not os.path.exists(save_path):
    os.mkdir(save_path)

In [4]:
ambient_folder = os.path.join(data_root, 'ambient')

In [5]:
ambient_files = os.listdir(ambient_folder)

In [6]:
ambient_df = pd.DataFrame({})
attack_df = pd.DataFrame({})

In [7]:
for file in ambient_files:
    if os.path.splitext(file)[-1] == '.csv':
        full_path = os.path.join(ambient_folder, file)
    
        this_csv = pd.read_csv(full_path)

        is_ambient = file.split('_')[0]
        if is_ambient == 'ambient':
            ambient_df = pd.concat([ambient_df, this_csv])
        else:
            attack_df = pd.concat([attack_df, this_csv])

In [8]:
ambient_df

,Label,Time,ID,Signal_1_of_ID,Signal_2_of_ID,Signal_3_of_ID,Signal_4_of_ID,Signal_5_of_ID,Signal_6_of_ID,Signal_7_of_ID,...,Signal_13_of_ID,Signal_14_of_ID,Signal_15_of_ID,Signal_16_of_ID,Signal_17_of_ID,Signal_18_of_ID,Signal_19_of_ID,Signal_20_of_ID,Signal_21_of_ID,Signal_22_of_ID
0,0,0.000000e+00,244,1,2.0,0.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,9.536743e-07,813,0,0.0,0.0,0.0,0.0,117.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,1.019955e-03,1694,2,126.0,127.0,0.0,170.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,1.020908e-03,293,0,0.0,256.0,262.0,1.0,-13.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,2.917051e-03,737,0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8264931,0,3.764317e+03,1760,0,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8264932,0,3.764317e+03,192,3,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8264933,0,3.764318e+03,1644,1,0.0,0.0,0.0,1.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8264934,0,3.764318e+03,1176,4095,4095.0,246.0,0.0,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8264935,0,3.764318e+03,813,1,0.0,0.0,0.0,0.0,102.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
attack_df

,Label,Time,ID,Signal_1_of_ID,Signal_2_of_ID,Signal_3_of_ID,Signal_4_of_ID,Signal_5_of_ID,Signal_6_of_ID,Signal_7_of_ID,...,Signal_13_of_ID,Signal_14_of_ID,Signal_15_of_ID,Signal_16_of_ID,Signal_17_of_ID,Signal_18_of_ID,Signal_19_of_ID,Signal_20_of_ID,Signal_21_of_ID,Signal_22_of_ID
0,0,0.000000,1413,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0.000002,852,32765,0.0,120.0,11.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0.000003,1505,511,1.0,3.0,1.0,0.0,32768.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0.000004,651,0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0.000994,167,0,0.0,0.0,2.0,529.0,1.0,593.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143999,0,64.257769,813,0,0.0,0.0,0.0,0.0,10.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144000,0,64.258767,737,0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144001,0,64.258769,852,32765,0.0,119.0,12.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144002,0,64.258770,961,1,0.0,242.0,7.0,136.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144003,0,64.258771,1505,511,2.0,3.0,1.0,0.0,32768.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
ambient_df['Label'].value_counts()

0    22620571
Name: Label, dtype: int64

In [11]:
attack_df['Label'].value_counts()

0    2217698
1      30728
Name: Label, dtype: int64

In [27]:
ambient_df.to_csv(os.path.join(data_root, 'ambient.csv'))

In [28]:
attack_df.to_csv(os.path.join(data_root, 'attack.csv'))

In [ ]:
ambient_df = pd.read_csv(os.path.join(data_root, 'ambient.csv'))
attack_df = pd.read_csv(os.path.join(data_root, 'attack.csv'))

In [9]:
def one_hot_vector(c):
    
    # 1  2  3  4  5  6  7  8  9  0  a  b  c  d  e  f
    
    ohv = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    
    if c == '1':
        ohv[0] = 255
    elif c == '2':
        ohv[1] = 255
    elif c == '3':
        ohv[2] = 255
    elif c == '4':
        ohv[3] = 255
    elif c == '5':
        ohv[4] = 255
    elif c == '6':
        ohv[5] = 255
    elif c == '7':
        ohv[6] = 255
    elif c == '8':
        ohv[7] = 255
    elif c == '9':
        ohv[8] = 255
    elif c == '0':
        ohv[9] = 255
    elif c == 'a':
        ohv[10] = 255
    elif c == 'b':
        ohv[11] = 255
    elif c == 'c':
        ohv[12] = 255
    elif c == 'd':
        ohv[13] = 255
    elif c == 'e':
        ohv[14] = 255
    elif c == 'f':
        ohv[15] = 255
        
    return ohv

In [10]:
def data_to_one_hot_vector(can):
    
    can = np.array(list(str(hex(can))))  # '0x---' -> ['0', 'x', '-', '-', '-']
    can = can[2:]
    
    can = np.pad(can, (3 - len(can), 0), mode='constant', constant_values='0')

    c1 = one_hot_vector(can[0])
    c2 = one_hot_vector(can[1])
    c3 = one_hot_vector(can[2])

    image_can = np.concatenate((c1,c2,c3), axis=0)
    
    return image_can

In [19]:
def make_can_image(data, flag):
    
    row_size = 64
    col_size = 48

    # 16 x ( 3 x 64 )

    img_num = 0
    
    for i, f in zip(range(0, len(data), row_size), flag):
        can_image = np.zeros((1, col_size))
        loc = data.iloc[i : i + row_size]

        for j in range(0, len(loc)):
            new_vec = data_to_one_hot_vector(loc.iloc[j])
            can_image = np.vstack([can_image, new_vec])
        can_image = np.delete(can_image, (0), axis=0)

        can_image = Image.fromarray(can_image.astype(np.uint8))

        can_image.save(save_path + '/{}_{}.png'.format(f, img_num))
        img_num += 1

        if img_num % 10000 == 0:

            print('{}th data in process...'.format(img_num))

    print('Done converting to {} images'.format(img_num))

In [29]:
df = pd.concat([ambient_df, attack_df])

In [30]:
df.to_csv(os.path.join(data_root, 'df.csv'))

In [12]:
df = pd.read_csv(os.path.join(data_root, 'df.csv'))

In [13]:
df

,Unnamed: 0,Label,Time,ID,Signal_1_of_ID,Signal_2_of_ID,Signal_3_of_ID,Signal_4_of_ID,Signal_5_of_ID,Signal_6_of_ID,...,Signal_13_of_ID,Signal_14_of_ID,Signal_15_of_ID,Signal_16_of_ID,Signal_17_of_ID,Signal_18_of_ID,Signal_19_of_ID,Signal_20_of_ID,Signal_21_of_ID,Signal_22_of_ID
0,0,0,0.000000e+00,244,1,2.0,0.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,9.536743e-07,813,0,0.0,0.0,0.0,0.0,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0,1.019955e-03,1694,2,126.0,127.0,0.0,170.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0,1.020908e-03,293,0,0.0,256.0,262.0,1.0,-13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0,2.917051e-03,737,0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24868992,143999,0,6.425777e+01,813,0,0.0,0.0,0.0,0.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24868993,144000,0,6.425877e+01,737,0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24868994,144001,0,6.425877e+01,852,32765,0.0,119.0,12.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24868995,144002,0,6.425877e+01,961,1,0.0,242.0,7.0,136.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24868996,144003,0,6.425877e+01,1505,511,2.0,3.0,1.0,0.0,32768.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
id_df = df.ID

In [15]:
id_df

0            244
1            813
2           1694
3            293
4            737
            ...
24868992     813
24868993     737
24868994     852
24868995     961
24868996    1505
Name: ID, Length: 24868997, dtype: int64

In [16]:
def check_flags(df):
    
    res = []
    
    for i in range(0, len(df), 64):
        
        check_range = df.iloc[i:i+64]
        
        # 1 if abnormal, 0 if normal
        if 1 in check_range.values:
            res.append(1)
        else:
            res.append(0)
        
    return res

In [17]:
flags = check_flags(id_df)

In [20]:
make_can_image(id_df, flags)

10000th data in process...
20000th data in process...
30000th data in process...
40000th data in process...
50000th data in process...
60000th data in process...
70000th data in process...
80000th data in process...
90000th data in process...
100000th data in process...
110000th data in process...
120000th data in process...
130000th data in process...
140000th data in process...
150000th data in process...
160000th data in process...
170000th data in process...
180000th data in process...
190000th data in process...
200000th data in process...
210000th data in process...
220000th data in process...
230000th data in process...
240000th data in process...
250000th data in process...
260000th data in process...
270000th data in process...
280000th data in process...
290000th data in process...
300000th data in process...
310000th data in process...
320000th data in process...
330000th data in process...
340000th data in process...
350000th data in process...
360000th data in process...
370000th data in process...
380000th data in process...
Done converting to 388579 images